### ISSUE TITLE
"ERROR: unexpected end of JSON input"

### ISSUE THREAD

**Issue by dmolina** [chasinglogic/dfm#42] opened 2017-11-18 11:36 UTC
I have download your nice program,  but I could not use it. 
I have try with the github version (with 'go get')  and the release  version (on a Ubuntu 17.04, with go version 1.7.4, and also with go 1.9.2)

The output is the following:
'$ dfm
Which backend would you like to use? [git, dropbox] (Default: git) 

NOTE: Some backends will change this automatically and override your setting. (i.e. dropbox)
Where would you like to store profiles? (Default: /mnt/home/daniel/.config/dfm) 
{
	"Backend": "git",
	"ConfigDir": "/mnt/home/daniel/.config/dfm",
	"CurrentProfile": "",
	"Etc": null
}
Does this look correct? Y/n: Y
ERROR: unexpected end of JSON input
' 

Any ideas about the error? 

Thanks in advance.

**Comment by chasinglogic** [comment] 2017-11-18 17:09
This was caused by the setupWizard function not saving the config and then the init would go on to try and load the config from a non-existent file. I've fixed this and pushed the fix and made a new release. You should be able to get the update with `go get -u github.com/chasinglogic/dfm`

**Closed as completed** 2017-11-18 17:09 UTC
